modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0-or-later"

[[mods]]
modId = "wurst"
version = "7.51.2"
displayName = "Wurst Client"
authors = "Alexander01998"
description = '''
Wurst Client for NeoForge - Wurst Wurst Wurst!
'''
#logoFile = ""

[[dependencies.wurst]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.wurst]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "polarbear.mixins.json"
